version: '3.8'
services: 
  wordpress:
    image: wordpress
    volumes:
      - /efs/website:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: projeto02-rds.cj8e4qgw0xn6.us-east-1.rds.amazonaws.com 
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: Projeto02_DataBase
      WORDPRESS_TABLE_CONFIG: wp_"
